export const AaveLendingPoolV2 = [
  'function FLASHLOAN_PREMIUM_TOTAL() view returns (uint256)',
  'function LENDINGPOOL_REVISION() view returns (uint256)',
  'function MAX_NUMBER_RESERVES() view returns (uint256)',
  'function MAX_STABLE_RATE_BORROW_SIZE_PERCENT() view returns (uint256)',
  'function borrow(address asset, uint256 amount, uint256 interestRateMode, uint16 referralCode, address onBehalfOf)',
  'function deposit(address asset, uint256 amount, address onBehalfOf, uint16 referralCode)',
  'function finalizeTransfer(address asset, address from, address to, uint256 amount, uint256 balanceFromBefore, uint256 balanceToBefore)',
  'function flashLoan(address receiverAddress, address[] assets, uint256[] amounts, uint256[] modes, address onBehalfOf, bytes params, uint16 referralCode)',
  'function getAddressesProvider() view returns (address)',
  'function getConfiguration(address asset) view returns ((uint256 data))',
  'function getReserveData(address asset) view returns (((uint256 data) configuration, uint128 liquidityIndex, uint128 variableBorrowIndex, uint128 currentLiquidityRate, uint128 currentVariableBorrowRate, uint128 currentStableBorrowRate, uint40 lastUpdateTimestamp, address aTokenAddress, address stableDebtTokenAddress, address variableDebtTokenAddress, address interestRateStrategyAddress, uint8 id))',
  'function getReserveNormalizedIncome(address asset) view returns (uint256)',
  'function getReserveNormalizedVariableDebt(address asset) view returns (uint256)',
  'function getReservesList() view returns (address[])',
  'function getUserAccountData(address user) view returns (uint256 totalCollateralETH, uint256 totalDebtETH, uint256 availableBorrowsETH, uint256 currentLiquidationThreshold, uint256 ltv, uint256 healthFactor)',
  'function getUserConfiguration(address user) view returns ((uint256 data))',
  'function initReserve(address asset, address aTokenAddress, address stableDebtAddress, address variableDebtAddress, address interestRateStrategyAddress)',
  'function initialize(address provider)',
  'function liquidationCall(address collateralAsset, address debtAsset, address user, uint256 debtToCover, bool receiveAToken)',
  'function paused() view returns (bool)',
  'function rebalanceStableBorrowRate(address asset, address user)',
  'function repay(address asset, uint256 amount, uint256 rateMode, address onBehalfOf) returns (uint256)',
  'function setConfiguration(address asset, uint256 configuration)',
  'function setPause(bool val)',
  'function setReserveInterestRateStrategyAddress(address asset, address rateStrategyAddress)',
  'function setUserUseReserveAsCollateral(address asset, bool useAsCollateral)',
  'function swapBorrowRateMode(address asset, uint256 rateMode)',
  'function withdraw(address asset, uint256 amount, address to) returns (uint256)'
]

export const AaveWethGatewayV2 = [
  'function authorizeLendingPool(address lendingPool)',
  'function borrowETH(address lendingPool, uint256 amount, uint256 interesRateMode, uint16 referralCode)',
  'function depositETH(address lendingPool, address onBehalfOf, uint16 referralCode) payable',
  'function emergencyEtherTransfer(address to, uint256 amount)',
  'function emergencyTokenTransfer(address token, address to, uint256 amount)',
  'function getWETHAddress() view returns (address)',
  'function owner() view returns (address)',
  'function renounceOwnership()',
  'function repayETH(address lendingPool, uint256 amount, uint256 rateMode, address onBehalfOf) payable',
  'function transferOwnership(address newOwner)',
  'function withdrawETH(address lendingPool, uint256 amount, address to)'
]

export const AaveV3Pool = [
  'function ADDRESSES_PROVIDER() view returns (address)',
  'function BRIDGE_PROTOCOL_FEE() view returns (uint256)',
  'function FLASHLOAN_PREMIUM_TOTAL() view returns (uint128)',
  'function FLASHLOAN_PREMIUM_TO_PROTOCOL() view returns (uint128)',
  'function MAX_NUMBER_RESERVES() view returns (uint16)',
  'function POOL_REVISION() view returns (uint256)',
  'function backUnbacked(address asset, uint256 amount, uint256 fee) returns (uint256)',
  'function borrow(address asset, uint256 amount, uint256 interestRateMode, uint16 referralCode, address onBehalfOf)',
  'function borrow(bytes32 args)',
  'function configureEModeCategory(uint8 id, (uint16 ltv, uint16 liquidationThreshold, uint16 liquidationBonus, string label) category)',
  'function configureEModeCategoryBorrowableBitmap(uint8 id, uint128 borrowableBitmap)',
  'function configureEModeCategoryCollateralBitmap(uint8 id, uint128 collateralBitmap)',
  'function deposit(address asset, uint256 amount, address onBehalfOf, uint16 referralCode)',
  'function dropReserve(address asset)',
  'function finalizeTransfer(address asset, address from, address to, uint256 amount, uint256 balanceFromBefore, uint256 balanceToBefore)',
  'function flashLoan(address receiverAddress, address[] assets, uint256[] amounts, uint256[] interestRateModes, address onBehalfOf, bytes params, uint16 referralCode)',
  'function flashLoanSimple(address receiverAddress, address asset, uint256 amount, bytes params, uint16 referralCode)',
  'function getBorrowLogic() pure returns (address)',
  'function getBridgeLogic() pure returns (address)',
  'function getConfiguration(address asset) view returns ((uint256 data))',
  'function getEModeCategoryBorrowableBitmap(uint8 id) view returns (uint128)',
  'function getEModeCategoryCollateralBitmap(uint8 id) view returns (uint128)',
  'function getEModeCategoryCollateralConfig(uint8 id) view returns ((uint16 ltv, uint16 liquidationThreshold, uint16 liquidationBonus))',
  'function getEModeCategoryData(uint8 id) view returns ((uint16 ltv, uint16 liquidationThreshold, uint16 liquidationBonus, address priceSource, string label))',
  'function getEModeCategoryLabel(uint8 id) view returns (string)',
  'function getEModeLogic() pure returns (address)',
  'function getFlashLoanLogic() pure returns (address)',
  'function getLiquidationGracePeriod(address asset) returns (uint40)',
  'function getLiquidationLogic() pure returns (address)',
  'function getPoolLogic() pure returns (address)',
  'function getReserveAddressById(uint16 id) view returns (address)',
  'function getReserveData(address asset) view returns (((uint256 data) configuration, uint128 liquidityIndex, uint128 currentLiquidityRate, uint128 variableBorrowIndex, uint128 currentVariableBorrowRate, uint128 currentStableBorrowRate, uint40 lastUpdateTimestamp, uint16 id, address aTokenAddress, address stableDebtTokenAddress, address variableDebtTokenAddress, address interestRateStrategyAddress, uint128 accruedToTreasury, uint128 unbacked, uint128 isolationModeTotalDebt))',
  'function getReserveDataExtended(address asset) view returns (((uint256 data) configuration, uint128 liquidityIndex, uint128 currentLiquidityRate, uint128 variableBorrowIndex, uint128 currentVariableBorrowRate, uint128 __deprecatedStableBorrowRate, uint40 lastUpdateTimestamp, uint16 id, uint40 liquidationGracePeriodUntil, address aTokenAddress, address __deprecatedStableDebtTokenAddress, address variableDebtTokenAddress, address interestRateStrategyAddress, uint128 accruedToTreasury, uint128 unbacked, uint128 isolationModeTotalDebt, uint128 virtualUnderlyingBalance))',
  'function getReserveNormalizedIncome(address asset) view returns (uint256)',
  'function getReserveNormalizedVariableDebt(address asset) view returns (uint256)',
  'function getReservesCount() view returns (uint256)',
  'function getReservesList() view returns (address[])',
  'function getSupplyLogic() pure returns (address)',
  'function getUserAccountData(address user) view returns (uint256 totalCollateralBase, uint256 totalDebtBase, uint256 availableBorrowsBase, uint256 currentLiquidationThreshold, uint256 ltv, uint256 healthFactor)',
  'function getUserConfiguration(address user) view returns ((uint256 data))',
  'function getUserEMode(address user) view returns (uint256)',
  'function getVirtualUnderlyingBalance(address asset) view returns (uint128)',
  'function initReserve(address asset, address aTokenAddress, address variableDebtAddress, address interestRateStrategyAddress)',
  'function initialize(address provider)',
  'function liquidationCall(address collateralAsset, address debtAsset, address user, uint256 debtToCover, bool receiveAToken)',
  'function liquidationCall(bytes32 args1, bytes32 args2)',
  'function mintToTreasury(address[] assets)',
  'function mintUnbacked(address asset, uint256 amount, address onBehalfOf, uint16 referralCode)',
  'function repay(bytes32 args) returns (uint256)',
  'function repay(address asset, uint256 amount, uint256 interestRateMode, address onBehalfOf) returns (uint256)',
  'function repayWithATokens(address asset, uint256 amount, uint256 interestRateMode) returns (uint256)',
  'function repayWithATokens(bytes32 args) returns (uint256)',
  'function repayWithPermit(bytes32 args, bytes32 r, bytes32 s) returns (uint256)',
  'function repayWithPermit(address asset, uint256 amount, uint256 interestRateMode, address onBehalfOf, uint256 deadline, uint8 permitV, bytes32 permitR, bytes32 permitS) returns (uint256)',
  'function rescueTokens(address token, address to, uint256 amount)',
  'function resetIsolationModeTotalDebt(address asset)',
  'function setConfiguration(address asset, (uint256 data) configuration)',
  'function setLiquidationGracePeriod(address asset, uint40 until)',
  'function setReserveInterestRateStrategyAddress(address asset, address rateStrategyAddress)',
  'function setUserEMode(uint8 categoryId)',
  'function setUserUseReserveAsCollateral(bytes32 args)',
  'function setUserUseReserveAsCollateral(address asset, bool useAsCollateral)',
  'function supply(address asset, uint256 amount, address onBehalfOf, uint16 referralCode)',
  'function supply(bytes32 args)',
  'function supplyWithPermit(address asset, uint256 amount, address onBehalfOf, uint16 referralCode, uint256 deadline, uint8 permitV, bytes32 permitR, bytes32 permitS)',
  'function supplyWithPermit(bytes32 args, bytes32 r, bytes32 s)',
  'function syncIndexesState(address asset)',
  'function syncRatesState(address asset)',
  'function updateBridgeProtocolFee(uint256 protocolFee)',
  'function updateFlashloanPremiums(uint128 flashLoanPremiumTotal, uint128 flashLoanPremiumToProtocol)',
  'function withdraw(address asset, uint256 amount, address to) returns (uint256)',
  'function withdraw(bytes32 args) returns (uint256)'
]
