export const UPDATE_SWAP_AND_BRIDGE_QUOTE_INTERVAL = 60000 // 1 minute
export const ACTIVITY_REFRESH_INTERVAL = 5000 // 5 seconds
export const ACTIVE_EXTENSION_DEFI_POSITIONS_UPDATE_INTERVAL = 300000 // 5 minutes
export const ACTIVE_EXTENSION_PORTFOLIO_UPDATE_INTERVAL = 60000 // 1 minute
export const INACTIVE_EXTENSION_PORTFOLIO_UPDATE_INTERVAL = 600000 // 10 minutes
export const ACCOUNT_STATE_PENDING_INTERVAL = 8000 // 8 seconds
export const ACCOUNT_STATE_STAND_BY_INTERVAL = 300000 // 5 minutes
