/**
 * A non-exclusive list of networks that Safe accounts are supported on.
 * We will use this list to know where to search for Safe accounts
 * and in accordance with the enabled user networks
 */
export const SAFE_NETWORKS = [
  1, 10, 56, 100, 130, 137, 143, 146, 480, 999, 5000, 8453, 9745, 42161, 42220, 43114, 57073, 59144,
  747474, 4326, 8217, 4663, 534352, 5042
]

export const SAFE_API_TIMEOUT_MS = 15000

export const SAFE_DEPLOYMENT_UNAVAILABLE_MESSAGE =
  "We can't activate this Safe account on this network. To use it here, activate it in the Safe app first."

// Keep Safe Transaction Service requests below its bulk request limits.
export const SAFE_API_BATCH_SIZE = 4

/**
 * SimulateTxAccessor addresses by Safe version.
 */
export const safeSimulateTxAccessor = {
  ['v1.3.0']: '0x59AD6735bCd8152B84860Cb256dD9e96b85F69Da',
  ['v1.4.1']: '0x3d4BA2E0884aa488718476ca2FB8Efc291A46199',
  ['v1.5.0']: '0x07EfA797c55B5DdE3698d876b277aBb6B893654C'
}

/**
 * Safe singletons (master copies) that a Safe proxy may be resolved to when looking up its
 * ERC-7730 descriptor. Any contract can put any address in its storage slot 0, so following
 * a proxy to an arbitrary address would let it borrow the descriptor of any registered protocol.
 * Lowercase; the addresses are the same on every chain.
 */
export const KNOWN_SAFE_SINGLETONS = new Set([
  '0xd9db270c1b5e3bd161e8c8503c55ceabee709552', // Safe v1.3.0
  '0x69f4d1788e39c87893c980c06edf4b7f686e2938', // Safe v1.3.0 (eip155)
  '0x3e5c63644e683549055b9be8653de26e0b4cd36e', // SafeL2 v1.3.0
  '0xfb1bffc9d739b8d520daf37df666da4c687191ea', // SafeL2 v1.3.0 (eip155)
  '0x41675c099f32341bf84bfc5382af534df5c7461a', // Safe v1.4.1
  '0x29fcb43b46531bca003ddc8fcb67ffe91900c762', // SafeL2 v1.4.1
  '0xff51a5898e281db6dfc7855790607438df2ca44b', // Safe v1.5.0
  '0xedd160febbd92e350d4d398fb636302fccd67c7e' // SafeL2 v1.5.0
])

/**
 * keccak256 of the runtime code of the official SafeProxy contracts. The proxy keeps its
 * singleton in storage, so the code is the same for every proxy of a given version and chain.
 * Older proxy versions are kept because an upgraded Safe keeps its original proxy code.
 * Generated by running each SafeProxyFactory's `proxyCreationCode()` and checked against
 * deployed Safes on Ethereum, Base and Optimism.
 */
export const KNOWN_SAFE_PROXY_CODE_HASHES = new Set([
  '0xf8fffcb9b9c73fbc4ffb6dc52f0001fa998951e0d4177894b1b899f7732b6eaf', // v1.0.0
  '0xaea7d4252f6245f301e540cfbee27d3a88de543af8e49c5c62405d5499fab7e5', // v1.1.1, v1.2.0
  '0xb89c1b3bdf2cf8827818646bce9a8f6e372885f8c55e5c07acbd307cb133b000', // v1.3.0
  '0xd7d408ebcd99b2b70be43e20253d6d92a8ea8fab29bd3be7f55b10032331fb4c', // v1.4.1
  '0x4e381985ca68b3e5d27b4425fa581c19cf33146d3f887a3cfca96f55528ea46f' // v1.5.0
])

export const execTransactionAbi = [
  'function execTransaction(address to,uint256 value,bytes calldata data,uint8 operation,uint256 safeTxGas,uint256 baseGas,uint256 gasPrice,address gasToken,address payable refundReceiver,bytes memory signatures)'
]
/**
 * In order to do batching, Safe needs an extra contract helper called multisend
 * This is the latest contract and it's safe to use across versions
 */
export const multiSendAddr = '0x9641d764fc13c8B624c04430C7356C1C7C8102e2'

export const safeNullOwner = '0x0000000000000000000000000000000000000002'

export const allowedMulticallContracts = [
  multiSendAddr,
  '0xA83c336B20401Af773B6219BA5027174338D1836',
  '0x40A2aCCbd92BCA938b02010E17A5b8929b49130D',
  '0xA1dabEF33b3B82c7814B6D82A79e50F4AC44102B',
  '0x8D29bE29923b68abfDD21e541b9374737B49cdAD'
]

/**
 * Known default Safe fallback handler addresses (CompatibilityFallbackHandler).
 * Any other fallback handler (e.g. an ExtensibleFallbackHandler used to register
 * per-domain EIP-1271 signature verifiers) can change how the Safe validates
 * signatures and should be flagged for user review.
 */
export const allowedFallbackHandlers = [
  '0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4', // CompatibilityFallbackHandler v1.3.0
  '0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99' // CompatibilityFallbackHandler v1.4.1
]
